//This file is generated by the EnumGenerator AssetPostprocessor.
//It should not be changed by hand
public enum WagonNames
{
    Cattle,
    Locomotive,
    Vagon1,
    Vagon2
}

public enum TowerNames
{
    Canon,
    Turret
}